#! /bin/sh
cp -r $(kpsewhich urml.tfm) urml.tfm
cp -r $(kpsewhich urmlv.tfm) urmlv.tfm

cp -r urml.tfm upml-a.tfm
cp -r urml.tfm upmr-a.tfm
cp -r urml.tfm upmb-a.tfm
cp -r urml.tfm upgr-a.tfm
cp -r urml.tfm upgb-a.tfm
cp -r urml.tfm upge-a.tfm
cp -r urml.tfm upmg-a.tfm
cp -r urml.tfm upml-aq.tfm
cp -r urml.tfm upmr-aq.tfm
cp -r urml.tfm upmb-aq.tfm
cp -r urml.tfm upgr-aq.tfm
cp -r urml.tfm upgb-aq.tfm
cp -r urml.tfm upge-aq.tfm
cp -r urml.tfm upmg-aq.tfm
cp -r urmlv.tfm utml-a.tfm
cp -r urmlv.tfm utmr-a.tfm
cp -r urmlv.tfm utmb-a.tfm
cp -r urmlv.tfm utgr-a.tfm
cp -r urmlv.tfm utgb-a.tfm
cp -r urmlv.tfm utge-a.tfm
cp -r urmlv.tfm utmg-a.tfm
cp -r urml.tfm symt-ah.tfm
cp -r urml.tfm symt-bh.tfm
cp -r urml.tfm symt-ch.tfm
cp -r urml.tfm symt-dh.tfm
cp -r urml.tfm symt-eh.tfm
cp -r urml.tfm symt-fh.tfm
cp -r urml.tfm symt-aq.tfm
cp -r urml.tfm symt-bq.tfm
cp -r urml.tfm symt-cq.tfm
cp -r urml.tfm symt-dq.tfm
cp -r urml.tfm symt-eq.tfm
cp -r urml.tfm symt-fq.tfm
cp -r urmlv.tfm symt-at.tfm
cp -r urmlv.tfm symt-bt.tfm
cp -r urmlv.tfm symt-ct.tfm
cp -r urmlv.tfm symt-dt.tfm
cp -r urmlv.tfm symt-et.tfm
cp -r urmlv.tfm symt-ft.tfm
cp -r urml.tfm upbw-a.tfm
cp -r urml.tfm upbw-b.tfm
cp -r urml.tfm upbw-c.tfm
cp -r urmlv.tfm utbw-a.tfm
cp -r urmlv.tfm utbw-b.tfm
cp -r urmlv.tfm utbw-c.tfm
cp -r urml.tfm upmg-hk.tfm
cp -r urmlv.tfm utmg-hk.tfm

cp -r urmlv.tfm utml-b.tfm
cp -r urmlv.tfm utmr-b.tfm
cp -r urmlv.tfm utmb-b.tfm
cp -r urmlv.tfm utgr-b.tfm
cp -r urmlv.tfm utgb-b.tfm
cp -r urmlv.tfm utge-b.tfm
cp -r urmlv.tfm utmg-b.tfm
cp -r urmlv.tfm utml-c.tfm
cp -r urmlv.tfm utmr-c.tfm
cp -r urmlv.tfm utmb-c.tfm
cp -r urmlv.tfm utgr-c.tfm
cp -r urmlv.tfm utgb-c.tfm
cp -r urmlv.tfm utge-c.tfm
cp -r urmlv.tfm utmg-c.tfm
cp -r urmlv.tfm utml-d.tfm
cp -r urmlv.tfm utmr-d.tfm
cp -r urmlv.tfm utmb-d.tfm
cp -r urmlv.tfm utgr-d.tfm
cp -r urmlv.tfm utgb-d.tfm
cp -r urmlv.tfm utge-d.tfm
cp -r urmlv.tfm utmg-d.tfm

